---
# Install MapR Pre-requisites software packages
  
  # Disable selinux
  - name: Set selinux config to disabled
    selinux: state=disabled policy=targeted

  - name: Selinux to permissive now
    command: setenforce permissive
    register: command_result
    failed_when: "command_result is failed and 'setenforce: SELinux is disabled' in command_result.msg"
    ignore_errors: yes

  # Check if running on Amazon EC2 machines
  - name: Check if running on Amazon EC2 machines
    shell: grep -s -o 'ec2' /sys/hypervisor/uuid | wc -l
    register: amazon_ec2_node

  # Enable extra repo for Docker installation on AWS
  - name: Enable extra repo for Docker installation on AWS
    shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"
    when: amazon_ec2_node.stdout == '1'
    ignore_errors: yes

