## Pre-requisites
- name: Apply pre-requisite configuration to all nodes
  hosts: mapr-retail-demo
  roles:
    - common-prereq-software

## Install Docker
- name: Install Docker
  hosts: mapr-retail-demo
  roles:
    - thirdparty-docker

## Install mapr-dsr
- name: Install mapr-dsr
  hosts: mapr-retail-demo
  roles:
    - mapr-dsr

## Install mapr-pacc-streamsets
- name: Install mapr-pacc-streamsets
  hosts: mapr-retail-demo
  roles:
    - mapr-pacc-streamsets

## Install mapr-retail-demo-cashregister
- name: Install mapr-retail-demo-cashregister
  hosts: mapr-retail-demo
  roles:
    - mapr-retail-demo-cashregister

## Create MapR Volume, DB's and Event Streams
- name: Create MapR Volume, DB's and Event Streams
  hosts: mapr-retail-demo
  roles:
    - mapr-retail-demo-config
